version: 2
branches:
  only:
    - master
jobs:
  build:
    working_directory: /app
    docker:
      - image: andreilupu/headless-chrome-shots:json
    steps:
      - checkout
      - run:
          name: Start screenshots
          command: cd /app && mkdir ss && mkdir json && ls
      - run: cd /app && node shot.js --configPath=./.circleci/config.json
      - store_artifacts:
          path: /app/json/
          destination: al/jsons

  notify:
    working_directory:
    docker:
      - image: andreilupu/headless-chrome-shots:json
    steps:
      - run:
          name: Notify server
          command: curl http://qa.code711.com/dev?project=my-patch-child --max-time=10

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - notify
