version: 2
branches:
  only:
    - master
jobs:
  build:
    working_directory: /tmp/app
    docker:
      - image: andreilupu/headless-chrome-shots:json
    steps:
      - checkout

      - run:
          name: Call the shots
          command: |
            set -ex
            cd /tmp/app
            node /tmp/chrome-shots/shot.js --configPath=/tmp/app/.circleci/config.json

      - store_artifacts:
          path: /tmp/app/json/
          destination: al/jsons

#  notify:
#    working_directory: /app
#    docker:
#      - image: andreilupu/headless-chrome-shots:json
#    steps:
#      - run:
#          name: Notify server
#          command: curl http://qa.code711.com/dev?project=my-patch-child --max-time=10
#
#workflows:
#  version: 2
#  build-test-and-deploy:
#    jobs:
#      - build
##      - notify
